version: '3.8'

services:

  web:
    container_name: local_web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/chat_db?schema=public
      - NEXT_PUBLIC_SERVER_URL=https://app.meetlocal.app
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=https://app.meetlocal.app
    env_file:
      - .env
    depends_on:
      - db
      - api
    networks:
      - local_network

  marketing:
    container_name: local_marketing
    build:
      context: .
      dockerfile: apps/web/Dockerfile.marketing
    restart: always
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=https://app.meetlocal.app
    env_file:
      - .env
    networks:
      - local_network

  api:
    container_name: local_api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/chat_db?schema=public
      - REDIS_URL=redis://redis:6379
      - API_PORT=3001
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - local_network

  db:
    image: postgres:15-alpine
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_network

  redis:
    image: redis:alpine
    container_name: local_redis
    restart: always
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  postgres_data:
